import = ["/var/home/mhoffm/.config/alacritty/dracula.toml"]

[font]
size = 12.5

[font.bold]
family = "monospace"
style = "Bold"

[font.bold_italic]
family = "monospace"
style = "Bold Italic"

[font.italic]
family = "monospace"
style = "Italic"

[font.normal]
family = "monospace"
style = "Regular"

[selection]
save_to_clipboard = true
